import { Country } from '@/types';

// Comprehensive list of countries with their currencies and phone codes
export const COUNTRIES: Country[] = [
  // Popular countries first
  { code: 'US', name: 'United States', currency: 'USD', phoneCode: '+1', flag: '🇺🇸' },
  { code: 'AU', name: 'Australia', currency: 'AUD', phoneCode: '+61', flag: '🇦🇺' },
  { code: 'IN', name: 'India', currency: 'INR', phoneCode: '+91', flag: '🇮🇳' },
  { code: 'GB', name: 'United Kingdom', currency: 'GBP', phoneCode: '+44', flag: '🇬🇧' },
  { code: 'CA', name: 'Canada', currency: 'CAD', phoneCode: '+1', flag: '🇨🇦' },
  { code: 'SG', name: 'Singapore', currency: 'SGD', phoneCode: '+65', flag: '🇸🇬' },
  
  // All other countries alphabetically
  { code: 'AD', name: 'Andorra', currency: 'EUR', phoneCode: '+376', flag: '🇦🇩' },
  { code: 'AE', name: 'United Arab Emirates', currency: 'AED', phoneCode: '+971', flag: '🇦🇪' },
  { code: 'AF', name: 'Afghanistan', currency: 'AFN', phoneCode: '+93', flag: '🇦🇫' },
  { code: 'AG', name: 'Antigua and Barbuda', currency: 'XCD', phoneCode: '+1', flag: '🇦🇬' },
  { code: 'AI', name: 'Anguilla', currency: 'XCD', phoneCode: '+1', flag: '🇦🇮' },
  { code: 'AL', name: 'Albania', currency: 'ALL', phoneCode: '+355', flag: '🇦🇱' },
  { code: 'AM', name: 'Armenia', currency: 'AMD', phoneCode: '+374', flag: '🇦🇲' },
  { code: 'AO', name: 'Angola', currency: 'AOA', phoneCode: '+244', flag: '🇦🇴' },
  { code: 'AR', name: 'Argentina', currency: 'ARS', phoneCode: '+54', flag: '🇦🇷' },
  { code: 'AS', name: 'American Samoa', currency: 'USD', phoneCode: '+1', flag: '🇦🇸' },
  { code: 'AT', name: 'Austria', currency: 'EUR', phoneCode: '+43', flag: '🇦🇹' },
  { code: 'AW', name: 'Aruba', currency: 'AWG', phoneCode: '+297', flag: '🇦🇼' },
  { code: 'AZ', name: 'Azerbaijan', currency: 'AZN', phoneCode: '+994', flag: '🇦🇿' },
  { code: 'BA', name: 'Bosnia and Herzegovina', currency: 'BAM', phoneCode: '+387', flag: '🇧🇦' },
  { code: 'BB', name: 'Barbados', currency: 'BBD', phoneCode: '+1', flag: '🇧🇧' },
  { code: 'BD', name: 'Bangladesh', currency: 'BDT', phoneCode: '+880', flag: '🇧🇩' },
  { code: 'BE', name: 'Belgium', currency: 'EUR', phoneCode: '+32', flag: '🇧🇪' },
  { code: 'BF', name: 'Burkina Faso', currency: 'XOF', phoneCode: '+226', flag: '🇧🇫' },
  { code: 'BG', name: 'Bulgaria', currency: 'BGN', phoneCode: '+359', flag: '🇧🇬' },
  { code: 'BH', name: 'Bahrain', currency: 'BHD', phoneCode: '+973', flag: '🇧🇭' },
  { code: 'BI', name: 'Burundi', currency: 'BIF', phoneCode: '+257', flag: '🇧🇮' },
  { code: 'BJ', name: 'Benin', currency: 'XOF', phoneCode: '+229', flag: '🇧🇯' },
  { code: 'BM', name: 'Bermuda', currency: 'BMD', phoneCode: '+1', flag: '🇧🇲' },
  { code: 'BN', name: 'Brunei', currency: 'BND', phoneCode: '+673', flag: '🇧🇳' },
  { code: 'BO', name: 'Bolivia', currency: 'BOB', phoneCode: '+591', flag: '🇧🇴' },
  { code: 'BR', name: 'Brazil', currency: 'BRL', phoneCode: '+55', flag: '🇧🇷' },
  { code: 'BS', name: 'Bahamas', currency: 'BSD', phoneCode: '+1', flag: '🇧🇸' },
  { code: 'BT', name: 'Bhutan', currency: 'BTN', phoneCode: '+975', flag: '🇧🇹' },
  { code: 'BW', name: 'Botswana', currency: 'BWP', phoneCode: '+267', flag: '🇧🇼' },
  { code: 'BY', name: 'Belarus', currency: 'BYN', phoneCode: '+375', flag: '🇧🇾' },
  { code: 'BZ', name: 'Belize', currency: 'BZD', phoneCode: '+501', flag: '🇧🇿' },
  { code: 'CD', name: 'Democratic Republic of the Congo', currency: 'CDF', phoneCode: '+243', flag: '🇨🇩' },
  { code: 'CF', name: 'Central African Republic', currency: 'XAF', phoneCode: '+236', flag: '🇨🇫' },
  { code: 'CG', name: 'Republic of the Congo', currency: 'XAF', phoneCode: '+242', flag: '🇨🇬' },
  { code: 'CH', name: 'Switzerland', currency: 'CHF', phoneCode: '+41', flag: '🇨🇭' },
  { code: 'CI', name: 'Ivory Coast', currency: 'XOF', phoneCode: '+225', flag: '🇨🇮' },
  { code: 'CK', name: 'Cook Islands', currency: 'NZD', phoneCode: '+682', flag: '🇨🇰' },
  { code: 'CL', name: 'Chile', currency: 'CLP', phoneCode: '+56', flag: '🇨🇱' },
  { code: 'CM', name: 'Cameroon', currency: 'XAF', phoneCode: '+237', flag: '🇨🇲' },
  { code: 'CN', name: 'China', currency: 'CNY', phoneCode: '+86', flag: '🇨🇳' },
  { code: 'CO', name: 'Colombia', currency: 'COP', phoneCode: '+57', flag: '🇨🇴' },
  { code: 'CR', name: 'Costa Rica', currency: 'CRC', phoneCode: '+506', flag: '🇨🇷' },
  { code: 'CU', name: 'Cuba', currency: 'CUP', phoneCode: '+53', flag: '🇨🇺' },
  { code: 'CV', name: 'Cape Verde', currency: 'CVE', phoneCode: '+238', flag: '🇨🇻' },
  { code: 'CY', name: 'Cyprus', currency: 'EUR', phoneCode: '+357', flag: '🇨🇾' },
  { code: 'CZ', name: 'Czech Republic', currency: 'CZK', phoneCode: '+420', flag: '🇨🇿' },
  { code: 'DE', name: 'Germany', currency: 'EUR', phoneCode: '+49', flag: '🇩🇪' },
  { code: 'DJ', name: 'Djibouti', currency: 'DJF', phoneCode: '+253', flag: '🇩🇯' },
  { code: 'DK', name: 'Denmark', currency: 'DKK', phoneCode: '+45', flag: '🇩🇰' },
  { code: 'DM', name: 'Dominica', currency: 'XCD', phoneCode: '+1', flag: '🇩🇲' },
  { code: 'DO', name: 'Dominican Republic', currency: 'DOP', phoneCode: '+1', flag: '🇩🇴' },
  { code: 'DZ', name: 'Algeria', currency: 'DZD', phoneCode: '+213', flag: '🇩🇿' },
  { code: 'EC', name: 'Ecuador', currency: 'USD', phoneCode: '+593', flag: '🇪🇨' },
  { code: 'EE', name: 'Estonia', currency: 'EUR', phoneCode: '+372', flag: '🇪🇪' },
  { code: 'EG', name: 'Egypt', currency: 'EGP', phoneCode: '+20', flag: '🇪🇬' },
  { code: 'ER', name: 'Eritrea', currency: 'ERN', phoneCode: '+291', flag: '🇪🇷' },
  { code: 'ES', name: 'Spain', currency: 'EUR', phoneCode: '+34', flag: '🇪🇸' },
  { code: 'ET', name: 'Ethiopia', currency: 'ETB', phoneCode: '+251', flag: '🇪🇹' },
  { code: 'FI', name: 'Finland', currency: 'EUR', phoneCode: '+358', flag: '🇫🇮' },
  { code: 'FJ', name: 'Fiji', currency: 'FJD', phoneCode: '+679', flag: '🇫🇯' },
  { code: 'FK', name: 'Falkland Islands', currency: 'FKP', phoneCode: '+500', flag: '🇫🇰' },
  { code: 'FM', name: 'Micronesia', currency: 'USD', phoneCode: '+691', flag: '🇫🇲' },
  { code: 'FO', name: 'Faroe Islands', currency: 'DKK', phoneCode: '+298', flag: '🇫🇴' },
  { code: 'FR', name: 'France', currency: 'EUR', phoneCode: '+33', flag: '🇫🇷' },
  { code: 'GA', name: 'Gabon', currency: 'XAF', phoneCode: '+241', flag: '🇬🇦' },
  { code: 'GD', name: 'Grenada', currency: 'XCD', phoneCode: '+1', flag: '🇬🇩' },
  { code: 'GE', name: 'Georgia', currency: 'GEL', phoneCode: '+995', flag: '🇬🇪' },
  { code: 'GF', name: 'French Guiana', currency: 'EUR', phoneCode: '+594', flag: '🇬🇫' },
  { code: 'GH', name: 'Ghana', currency: 'GHS', phoneCode: '+233', flag: '🇬🇭' },
  { code: 'GI', name: 'Gibraltar', currency: 'GIP', phoneCode: '+350', flag: '🇬🇮' },
  { code: 'GL', name: 'Greenland', currency: 'DKK', phoneCode: '+299', flag: '🇬🇱' },
  { code: 'GM', name: 'Gambia', currency: 'GMD', phoneCode: '+220', flag: '🇬🇲' },
  { code: 'GN', name: 'Guinea', currency: 'GNF', phoneCode: '+224', flag: '🇬🇳' },
  { code: 'GP', name: 'Guadeloupe', currency: 'EUR', phoneCode: '+590', flag: '🇬🇵' },
  { code: 'GQ', name: 'Equatorial Guinea', currency: 'XAF', phoneCode: '+240', flag: '🇬🇶' },
  { code: 'GR', name: 'Greece', currency: 'EUR', phoneCode: '+30', flag: '🇬🇷' },
  { code: 'GT', name: 'Guatemala', currency: 'GTQ', phoneCode: '+502', flag: '🇬🇹' },
  { code: 'GU', name: 'Guam', currency: 'USD', phoneCode: '+1', flag: '🇬🇺' },
  { code: 'GW', name: 'Guinea-Bissau', currency: 'XOF', phoneCode: '+245', flag: '🇬🇼' },
  { code: 'GY', name: 'Guyana', currency: 'GYD', phoneCode: '+592', flag: '🇬🇾' },
  { code: 'HK', name: 'Hong Kong', currency: 'HKD', phoneCode: '+852', flag: '🇭🇰' },
  { code: 'HN', name: 'Honduras', currency: 'HNL', phoneCode: '+504', flag: '🇭🇳' },
  { code: 'HR', name: 'Croatia', currency: 'EUR', phoneCode: '+385', flag: '🇭🇷' },
  { code: 'HT', name: 'Haiti', currency: 'HTG', phoneCode: '+509', flag: '🇭🇹' },
  { code: 'HU', name: 'Hungary', currency: 'HUF', phoneCode: '+36', flag: '🇭🇺' },
  { code: 'ID', name: 'Indonesia', currency: 'IDR', phoneCode: '+62', flag: '🇮🇩' },
  { code: 'IE', name: 'Ireland', currency: 'EUR', phoneCode: '+353', flag: '🇮🇪' },
  { code: 'IL', name: 'Israel', currency: 'ILS', phoneCode: '+972', flag: '🇮🇱' },
  { code: 'IM', name: 'Isle of Man', currency: 'GBP', phoneCode: '+44', flag: '🇮🇲' },
  { code: 'IQ', name: 'Iraq', currency: 'IQD', phoneCode: '+964', flag: '🇮🇶' },
  { code: 'IR', name: 'Iran', currency: 'IRR', phoneCode: '+98', flag: '🇮🇷' },
  { code: 'IS', name: 'Iceland', currency: 'ISK', phoneCode: '+354', flag: '🇮🇸' },
  { code: 'IT', name: 'Italy', currency: 'EUR', phoneCode: '+39', flag: '🇮🇹' },
  { code: 'JE', name: 'Jersey', currency: 'GBP', phoneCode: '+44', flag: '🇯🇪' },
  { code: 'JM', name: 'Jamaica', currency: 'JMD', phoneCode: '+1', flag: '🇯🇲' },
  { code: 'JO', name: 'Jordan', currency: 'JOD', phoneCode: '+962', flag: '🇯🇴' },
  { code: 'JP', name: 'Japan', currency: 'JPY', phoneCode: '+81', flag: '🇯🇵' },
  { code: 'KE', name: 'Kenya', currency: 'KES', phoneCode: '+254', flag: '🇰🇪' },
  { code: 'KG', name: 'Kyrgyzstan', currency: 'KGS', phoneCode: '+996', flag: '🇰🇬' },
  { code: 'KH', name: 'Cambodia', currency: 'KHR', phoneCode: '+855', flag: '🇰🇭' },
  { code: 'KI', name: 'Kiribati', currency: 'AUD', phoneCode: '+686', flag: '🇰🇮' },
  { code: 'KM', name: 'Comoros', currency: 'KMF', phoneCode: '+269', flag: '🇰🇲' },
  { code: 'KN', name: 'Saint Kitts and Nevis', currency: 'XCD', phoneCode: '+1', flag: '🇰🇳' },
  { code: 'KP', name: 'North Korea', currency: 'KPW', phoneCode: '+850', flag: '🇰🇵' },
  { code: 'KR', name: 'South Korea', currency: 'KRW', phoneCode: '+82', flag: '🇰🇷' },
  { code: 'KW', name: 'Kuwait', currency: 'KWD', phoneCode: '+965', flag: '🇰🇼' },
  { code: 'KY', name: 'Cayman Islands', currency: 'KYD', phoneCode: '+1', flag: '🇰🇾' },
  { code: 'KZ', name: 'Kazakhstan', currency: 'KZT', phoneCode: '+7', flag: '🇰🇿' },
  { code: 'LA', name: 'Laos', currency: 'LAK', phoneCode: '+856', flag: '🇱🇦' },
  { code: 'LB', name: 'Lebanon', currency: 'LBP', phoneCode: '+961', flag: '🇱🇧' },
  { code: 'LC', name: 'Saint Lucia', currency: 'XCD', phoneCode: '+1', flag: '🇱🇨' },
  { code: 'LI', name: 'Liechtenstein', currency: 'CHF', phoneCode: '+423', flag: '🇱🇮' },
  { code: 'LK', name: 'Sri Lanka', currency: 'LKR', phoneCode: '+94', flag: '🇱🇰' },
  { code: 'LR', name: 'Liberia', currency: 'LRD', phoneCode: '+231', flag: '🇱🇷' },
  { code: 'LS', name: 'Lesotho', currency: 'LSL', phoneCode: '+266', flag: '🇱🇸' },
  { code: 'LT', name: 'Lithuania', currency: 'EUR', phoneCode: '+370', flag: '🇱🇹' },
  { code: 'LU', name: 'Luxembourg', currency: 'EUR', phoneCode: '+352', flag: '🇱🇺' },
  { code: 'LV', name: 'Latvia', currency: 'EUR', phoneCode: '+371', flag: '🇱🇻' },
  { code: 'LY', name: 'Libya', currency: 'LYD', phoneCode: '+218', flag: '🇱🇾' },
  { code: 'MA', name: 'Morocco', currency: 'MAD', phoneCode: '+212', flag: '🇲🇦' },
  { code: 'MC', name: 'Monaco', currency: 'EUR', phoneCode: '+377', flag: '🇲🇨' },
  { code: 'MD', name: 'Moldova', currency: 'MDL', phoneCode: '+373', flag: '🇲🇩' },
  { code: 'ME', name: 'Montenegro', currency: 'EUR', phoneCode: '+382', flag: '🇲🇪' },
  { code: 'MG', name: 'Madagascar', currency: 'MGA', phoneCode: '+261', flag: '🇲🇬' },
  { code: 'MH', name: 'Marshall Islands', currency: 'USD', phoneCode: '+692', flag: '🇲🇭' },
  { code: 'MK', name: 'North Macedonia', currency: 'MKD', phoneCode: '+389', flag: '🇲🇰' },
  { code: 'ML', name: 'Mali', currency: 'XOF', phoneCode: '+223', flag: '🇲🇱' },
  { code: 'MM', name: 'Myanmar', currency: 'MMK', phoneCode: '+95', flag: '🇲🇲' },
  { code: 'MN', name: 'Mongolia', currency: 'MNT', phoneCode: '+976', flag: '🇲🇳' },
  { code: 'MO', name: 'Macau', currency: 'MOP', phoneCode: '+853', flag: '🇲🇴' },
  { code: 'MP', name: 'Northern Mariana Islands', currency: 'USD', phoneCode: '+1', flag: '🇲🇵' },
  { code: 'MQ', name: 'Martinique', currency: 'EUR', phoneCode: '+596', flag: '🇲🇶' },
  { code: 'MR', name: 'Mauritania', currency: 'MRU', phoneCode: '+222', flag: '🇲🇷' },
  { code: 'MS', name: 'Montserrat', currency: 'XCD', phoneCode: '+1', flag: '🇲🇸' },
  { code: 'MT', name: 'Malta', currency: 'EUR', phoneCode: '+356', flag: '🇲🇹' },
  { code: 'MU', name: 'Mauritius', currency: 'MUR', phoneCode: '+230', flag: '🇲🇺' },
  { code: 'MV', name: 'Maldives', currency: 'MVR', phoneCode: '+960', flag: '🇲🇻' },
  { code: 'MW', name: 'Malawi', currency: 'MWK', phoneCode: '+265', flag: '🇲🇼' },
  { code: 'MX', name: 'Mexico', currency: 'MXN', phoneCode: '+52', flag: '🇲🇽' },
  { code: 'MY', name: 'Malaysia', currency: 'MYR', phoneCode: '+60', flag: '🇲🇾' },
  { code: 'MZ', name: 'Mozambique', currency: 'MZN', phoneCode: '+258', flag: '🇲🇿' },
  { code: 'NA', name: 'Namibia', currency: 'NAD', phoneCode: '+264', flag: '🇳🇦' },
  { code: 'NC', name: 'New Caledonia', currency: 'XPF', phoneCode: '+687', flag: '🇳🇨' },
  { code: 'NE', name: 'Niger', currency: 'XOF', phoneCode: '+227', flag: '🇳🇪' },
  { code: 'NF', name: 'Norfolk Island', currency: 'AUD', phoneCode: '+672', flag: '🇳🇫' },
  { code: 'NG', name: 'Nigeria', currency: 'NGN', phoneCode: '+234', flag: '🇳🇬' },
  { code: 'NI', name: 'Nicaragua', currency: 'NIO', phoneCode: '+505', flag: '🇳🇮' },
  { code: 'NL', name: 'Netherlands', currency: 'EUR', phoneCode: '+31', flag: '🇳🇱' },
  { code: 'NO', name: 'Norway', currency: 'NOK', phoneCode: '+47', flag: '🇳🇴' },
  { code: 'NP', name: 'Nepal', currency: 'NPR', phoneCode: '+977', flag: '🇳🇵' },
  { code: 'NR', name: 'Nauru', currency: 'AUD', phoneCode: '+674', flag: '🇳🇷' },
  { code: 'NU', name: 'Niue', currency: 'NZD', phoneCode: '+683', flag: '🇳🇺' },
  { code: 'NZ', name: 'New Zealand', currency: 'NZD', phoneCode: '+64', flag: '🇳🇿' },
  { code: 'OM', name: 'Oman', currency: 'OMR', phoneCode: '+968', flag: '🇴🇲' },
  { code: 'PA', name: 'Panama', currency: 'PAB', phoneCode: '+507', flag: '🇵🇦' },
  { code: 'PE', name: 'Peru', currency: 'PEN', phoneCode: '+51', flag: '🇵🇪' },
  { code: 'PF', name: 'French Polynesia', currency: 'XPF', phoneCode: '+689', flag: '🇵🇫' },
  { code: 'PG', name: 'Papua New Guinea', currency: 'PGK', phoneCode: '+675', flag: '🇵🇬' },
  { code: 'PH', name: 'Philippines', currency: 'PHP', phoneCode: '+63', flag: '🇵🇭' },
  { code: 'PK', name: 'Pakistan', currency: 'PKR', phoneCode: '+92', flag: '🇵🇰' },
  { code: 'PL', name: 'Poland', currency: 'PLN', phoneCode: '+48', flag: '🇵🇱' },
  { code: 'PM', name: 'Saint Pierre and Miquelon', currency: 'EUR', phoneCode: '+508', flag: '🇵🇲' },
  { code: 'PN', name: 'Pitcairn', currency: 'NZD', phoneCode: '+64', flag: '🇵🇳' },
  { code: 'PR', name: 'Puerto Rico', currency: 'USD', phoneCode: '+1', flag: '🇵🇷' },
  { code: 'PS', name: 'Palestine', currency: 'ILS', phoneCode: '+970', flag: '🇵🇸' },
  { code: 'PT', name: 'Portugal', currency: 'EUR', phoneCode: '+351', flag: '🇵🇹' },
  { code: 'PW', name: 'Palau', currency: 'USD', phoneCode: '+680', flag: '🇵🇼' },
  { code: 'PY', name: 'Paraguay', currency: 'PYG', phoneCode: '+595', flag: '🇵🇾' },
  { code: 'QA', name: 'Qatar', currency: 'QAR', phoneCode: '+974', flag: '🇶🇦' },
  { code: 'RE', name: 'Réunion', currency: 'EUR', phoneCode: '+262', flag: '🇷🇪' },
  { code: 'RO', name: 'Romania', currency: 'RON', phoneCode: '+40', flag: '🇷🇴' },
  { code: 'RS', name: 'Serbia', currency: 'RSD', phoneCode: '+381', flag: '🇷🇸' },
  { code: 'RU', name: 'Russia', currency: 'RUB', phoneCode: '+7', flag: '🇷🇺' },
  { code: 'RW', name: 'Rwanda', currency: 'RWF', phoneCode: '+250', flag: '🇷🇼' },
  { code: 'SA', name: 'Saudi Arabia', currency: 'SAR', phoneCode: '+966', flag: '🇸🇦' },
  { code: 'SB', name: 'Solomon Islands', currency: 'SBD', phoneCode: '+677', flag: '🇸🇧' },
  { code: 'SC', name: 'Seychelles', currency: 'SCR', phoneCode: '+248', flag: '🇸🇨' },
  { code: 'SD', name: 'Sudan', currency: 'SDG', phoneCode: '+249', flag: '🇸🇩' },
  { code: 'SE', name: 'Sweden', currency: 'SEK', phoneCode: '+46', flag: '🇸🇪' },
  { code: 'SH', name: 'Saint Helena', currency: 'SHP', phoneCode: '+290', flag: '🇸🇭' },
  { code: 'SI', name: 'Slovenia', currency: 'EUR', phoneCode: '+386', flag: '🇸🇮' },
  { code: 'SJ', name: 'Svalbard and Jan Mayen', currency: 'NOK', phoneCode: '+47', flag: '🇸🇯' },
  { code: 'SK', name: 'Slovakia', currency: 'EUR', phoneCode: '+421', flag: '🇸🇰' },
  { code: 'SL', name: 'Sierra Leone', currency: 'SLE', phoneCode: '+232', flag: '🇸🇱' },
  { code: 'SM', name: 'San Marino', currency: 'EUR', phoneCode: '+378', flag: '🇸🇲' },
  { code: 'SN', name: 'Senegal', currency: 'XOF', phoneCode: '+221', flag: '🇸🇳' },
  { code: 'SO', name: 'Somalia', currency: 'SOS', phoneCode: '+252', flag: '🇸🇴' },
  { code: 'SR', name: 'Suriname', currency: 'SRD', phoneCode: '+597', flag: '🇸🇷' },
  { code: 'SS', name: 'South Sudan', currency: 'SSP', phoneCode: '+211', flag: '🇸🇸' },
  { code: 'ST', name: 'São Tomé and Príncipe', currency: 'STN', phoneCode: '+239', flag: '🇸🇹' },
  { code: 'SV', name: 'El Salvador', currency: 'USD', phoneCode: '+503', flag: '🇸🇻' },
  { code: 'SX', name: 'Sint Maarten', currency: 'ANG', phoneCode: '+1', flag: '🇸🇽' },
  { code: 'SY', name: 'Syria', currency: 'SYP', phoneCode: '+963', flag: '🇸🇾' },
  { code: 'SZ', name: 'Eswatini', currency: 'SZL', phoneCode: '+268', flag: '🇸🇿' },
  { code: 'TC', name: 'Turks and Caicos Islands', currency: 'USD', phoneCode: '+1', flag: '🇹🇨' },
  { code: 'TD', name: 'Chad', currency: 'XAF', phoneCode: '+235', flag: '🇹🇩' },
  { code: 'TF', name: 'French Southern Territories', currency: 'EUR', phoneCode: '+262', flag: '🇹🇫' },
  { code: 'TG', name: 'Togo', currency: 'XOF', phoneCode: '+228', flag: '🇹🇬' },
  { code: 'TH', name: 'Thailand', currency: 'THB', phoneCode: '+66', flag: '🇹🇭' },
  { code: 'TJ', name: 'Tajikistan', currency: 'TJS', phoneCode: '+992', flag: '🇹🇯' },
  { code: 'TK', name: 'Tokelau', currency: 'NZD', phoneCode: '+690', flag: '🇹🇰' },
  { code: 'TL', name: 'East Timor', currency: 'USD', phoneCode: '+670', flag: '🇹🇱' },
  { code: 'TM', name: 'Turkmenistan', currency: 'TMT', phoneCode: '+993', flag: '🇹🇲' },
  { code: 'TN', name: 'Tunisia', currency: 'TND', phoneCode: '+216', flag: '🇹🇳' },
  { code: 'TO', name: 'Tonga', currency: 'TOP', phoneCode: '+676', flag: '🇹🇴' },
  { code: 'TR', name: 'Turkey', currency: 'TRY', phoneCode: '+90', flag: '🇹🇷' },
  { code: 'TT', name: 'Trinidad and Tobago', currency: 'TTD', phoneCode: '+1', flag: '🇹🇹' },
  { code: 'TV', name: 'Tuvalu', currency: 'AUD', phoneCode: '+688', flag: '🇹🇻' },
  { code: 'TW', name: 'Taiwan', currency: 'TWD', phoneCode: '+886', flag: '🇹🇼' },
  { code: 'TZ', name: 'Tanzania', currency: 'TZS', phoneCode: '+255', flag: '🇹🇿' },
  { code: 'UA', name: 'Ukraine', currency: 'UAH', phoneCode: '+380', flag: '🇺🇦' },
  { code: 'UG', name: 'Uganda', currency: 'UGX', phoneCode: '+256', flag: '🇺🇬' },
  { code: 'UM', name: 'U.S. Minor Outlying Islands', currency: 'USD', phoneCode: '+1', flag: '🇺🇲' },
  { code: 'UY', name: 'Uruguay', currency: 'UYU', phoneCode: '+598', flag: '🇺🇾' },
  { code: 'UZ', name: 'Uzbekistan', currency: 'UZS', phoneCode: '+998', flag: '🇺🇿' },
  { code: 'VA', name: 'Vatican City', currency: 'EUR', phoneCode: '+39', flag: '🇻🇦' },
  { code: 'VC', name: 'Saint Vincent and the Grenadines', currency: 'XCD', phoneCode: '+1', flag: '🇻🇨' },
  { code: 'VE', name: 'Venezuela', currency: 'VES', phoneCode: '+58', flag: '🇻🇪' },
  { code: 'VG', name: 'British Virgin Islands', currency: 'USD', phoneCode: '+1', flag: '🇻🇬' },
  { code: 'VI', name: 'U.S. Virgin Islands', currency: 'USD', phoneCode: '+1', flag: '🇻🇮' },
  { code: 'VN', name: 'Vietnam', currency: 'VND', phoneCode: '+84', flag: '🇻🇳' },
  { code: 'VU', name: 'Vanuatu', currency: 'VUV', phoneCode: '+678', flag: '🇻🇺' },
  { code: 'WF', name: 'Wallis and Futuna', currency: 'XPF', phoneCode: '+681', flag: '🇼🇫' },
  { code: 'WS', name: 'Samoa', currency: 'WST', phoneCode: '+685', flag: '🇼🇸' },
  { code: 'YE', name: 'Yemen', currency: 'YER', phoneCode: '+967', flag: '🇾🇪' },
  { code: 'YT', name: 'Mayotte', currency: 'EUR', phoneCode: '+262', flag: '🇾🇹' },
  { code: 'ZA', name: 'South Africa', currency: 'ZAR', phoneCode: '+27', flag: '🇿🇦' },
  { code: 'ZM', name: 'Zambia', currency: 'ZMW', phoneCode: '+260', flag: '🇿🇲' },
  { code: 'ZW', name: 'Zimbabwe', currency: 'ZWL', phoneCode: '+263', flag: '🇿🇼' },
];

// Popular countries for quick access
export const POPULAR_COUNTRIES = COUNTRIES.slice(0, 6);

// All currencies from the countries list
export const CURRENCIES = Array.from(new Set(COUNTRIES.map(country => country.currency))).sort();